// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int32
	Task        string
	Completed   pgtype.Bool
	CreatedAt   pgtype.Timestamp
	Description pgtype.Text
}
